---
- name: Install and start Apache on Amazon Linux
  hosts: all
  become: yes  # Use sudo

  tasks:
    - name: Install httpd package
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Start and enable httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
